# Generated by Django 5.0.6 on 2024-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        help_text="size:500*755", upload_to="team", verbose_name="头像"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("title", models.CharField(max_length=100, verbose_name="职务")),
                ("rank", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "verbose_name": "团队管理",
                "verbose_name_plural": "团队管理",
                "db_table": "team",
            },
        ),
    ]
