# Generated by Django 5.0.6 on 2024-06-14 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="slide",
            table="slide",
        ),
    ]
